### ISSUE TITLE
AssertionError: Unable to infer the amount of nodes.

### ISSUE THREAD

**Issue by giaguaro** [20171130/Equivariant-NN-Zoo#1]
Thank you so much for this great repository. 
I was wondering if you could help me with figuring out how to prevent this error? I think this is happening because the object passed to collator from the dataloader is not a list and only the attributes are left when getting the next(iter(dataset)). I tried to unravel the batch object but I observed that the tensors of coordinates, for example, are all concatenated along the same dimension across all samples. Is this intended since we are relying on the edge_index? Also, I tried to calculate edge_index before passing the dataset but that did not help (is edge_index internally calculated if omitted from preparing the HDF5 dataset?)

Here is my traceback on the error I am facing: 

Traceback (most recent call last):
  File "train.py", line 311, in <module>
    launch_mp()
  File "train.py", line 295, in launch_mp
    main(0)
  File "train.py", line 278, in main
    train_regression(e3_config, FLAGS)
  File "train.py", line 72, in train_regression
    trainer.train()
  File "/content/drive/MyDrive/Colab_Notebooks/Equivariant-NN-Zoo/e3_layers/run/trainer.py", line 329, in train
    self.epoch_step()
  File "/content/drive/MyDrive/Colab_Notebooks/Equivariant-NN-Zoo-master/e3_layers/run/trainer.py", line 468, in epoch_step
    batch = next(iterable)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/content/drive/MyDrive/Colab_Notebooks/Equivariant-NN-Zoo-master/e3_layers/data/dataloader.py", line 31, in __call__
    return self.collate(batch)
  File "/content/drive/MyDrive/Colab_Notebooks/Equivariant-NN-Zoo/e3_layers/data/dataloader.py", line 26, in collate
    out = Batch.from_data_list(batch, attrs=batch[0].attrs)
  File "/content/drive/MyDrive/Colab_Notebooks/Equivariant-NN-Zoo/e3_layers/data/batch.py", line 58, in from_data_list
    assert node_key is not None, 'Unable to infer the amount of nodes.'
AssertionError: Unable to infer the amount of nodes.

**Comment by 20171130** [comment]
The error indicates that no tensor in the batch is marked as a node attribute. When constructing your dataset, you should mark the type of each tensor like this:
```
attrs = {}
attrs['pos'] = ('node', '1x1o')
attrs['atom_types'] = ('node', '1x0e')
attrs['dipole'] = ('node', '1x1o')
attrs['quadrupole_0'] = ('node', '1x0e')
attrs['quadrupole_2'] = ('node', '1x2e')

batch = Batch.from_data_list(lst, attrs)
```
It is intended that the whole batch is considered a large graph of samples as subgraphs. The advantage is that no padding is needed for storage and computation.

**Comment by giaguaro** [comment]
Thank you so much for your answer. I want to clarify that that I do not get this error when constructing the dataset. I assign attributes as you specified above and the batch file is written normally. Whereas I get this error during training after the processed dataset gets passed as a condensed dataset to the dataloader. I even tried all the processed datasets that was provided (across different configs) but I do get different errors, one of them is still the Assertion Error I caught before. None of the provided example HDF5 files seem to work with me for some reason. 
I am trying to train an energy_force config. Here are my attributes and tensors (am i doing anything wrong?):

attrs = {}
attrs['pos'] = ('node', '1x1o')
attrs['species'] = ('node', '1x0e')
attrs['forces'] = ('node', '1x1o')
attrs['energy'] = ('graph', '1x0e')

lst = []
for i in range(10):
    dic = {}
    dic['pos'] = torch.tensor(npz['R'][i])
    dic['species'] = torch.tensor(npz['z'])
    dic['forces'] = torch.tensor(npz['F'][i])
    dic['energy'] = torch.tensor(npz['E'][i])
    lst+=[dic]

batch = Batch.from_data_list(lst=lst, attrs=attrs)
batch.dumpHDF5('example.hdf5')
....
>>
Writing tensor _n_nodes.
Writing tensor pos.
Writing tensor species.
Writing tensor forces.
Writing tensor energy.
Writing attr pos=('node', '1x1o')
Writing attr species=('node', '1x0e')
Writing attr forces=('node', '1x1o')
Writing attr energy=('graph', '1x0e')
Writing attr _n_nodes=('graph', '1x0e')
Writing attr _n_edges=('graph', '1x0e')

**Comment by 20171130** [comment]
The following codes work fine for me. I am not sure what caused the errors for you. You can try setting `model.jit=false` in the config and passing `dataloader_num_workers=0` as a command line argument. Then you can debug the dataloader using [pdb](https://docs.python.org/3/library/pdb.html).

```
import torch
from e3_layers.data import Batch, CondensedDataset, DataLoader
attrs = {}
attrs['pos'] = ('node', '1x1o')

lst = []
for i in range(10):
    dic = {}
    dic['pos'] = torch.tensor(torch.zeros(i+1, 3))
    lst+=[dic]

batch = Batch.from_data_list(lst=lst, attrs=attrs)
batch.dumpHDF5('test.hdf5')
dataset = CondensedDataset('test.hdf5')
dataloader = DataLoader(dataset)
next(iter(dataloader))
```

**Comment by giaguaro** [comment]
Thank you so much for your help! I will try those.
